name: validate jsonld

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'INCF'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "12.x"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Checks that our JSON are valid
      - name: Check for syntax errors
        run: |
          npm install -g jsonlint
          grep -r  "@context" schemas | cut -d: -f1 | xargs -I fname jsonlint -q fname

      # Checks that the schemas are valid
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install reproschema requests_cache

      - name: Test with pyshacl
        run: |
          reproschema -l DEBUG validate schemas/artemis/protocols
          reproschema -l DEBUG validate schemas/artemis/activities
          reproschema -l DEBUG validate schemas/artemis/artemis_schema.jsonld
